/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/capitulos/{id_capitulo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Capitulo
         * @description Un capitulo de corrido: sus escenas en orden, cada una con estado y hallazgos.
         */
        get: operations["capitulo_capitulos__id_capitulo__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capitulos/{id_capitulo}/cerrar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cerrar Capitulo
         * @description La segunda puerta con firma humana.
         *
         *     Devuelve los `menor` que se dejan pasar: si no se enseñaran, `mayor` y
         *     `menor` volverian a producir el mismo comportamiento.
         */
        post: operations["cerrar_capitulo_capitulos__id_capitulo__cerrar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entrevistas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crear */
        post: operations["crear_entrevistas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entrevistas/{id_e}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar */
        get: operations["consultar_entrevistas__id_e__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entrevistas/{id_e}/cerrar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cerrar
         * @description El comprador confirma la ficha. `409` dice que lo impide, no solo que no.
         */
        post: operations["cerrar_entrevistas__id_e__cerrar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entrevistas/{id_e}/hechos/{id_h}/confirmar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirmar */
        post: operations["confirmar_entrevistas__id_e__hechos__id_h__confirmar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entrevistas/{id_e}/hechos/{id_h}/descartar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Descartar */
        post: operations["descartar_entrevistas__id_e__hechos__id_h__descartar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entrevistas/{id_e}/texto-libre": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Texto Libre */
        post: operations["texto_libre_entrevistas__id_e__texto_libre_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entrevistas/{id_e}/turnos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Historial
         * @description `SPEC-33` `RF-10`: la conversacion entera, en orden.
         */
        get: operations["historial_entrevistas__id_e__turnos_get"];
        put?: never;
        /** Turno */
        post: operations["turno_entrevistas__id_e__turnos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/escenas/{id_escena}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Escena
         * @description Una escena con su estado, sus hallazgos abiertos y su texto elegido (`RF-39`).
         */
        get: operations["escena_escenas__id_escena__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/escenas/{id_escena}/aceptar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aceptar
         * @description La dispara una persona. El worker no tiene ninguna ruta que llegue aqui.
         *
         *     `rindiendose` deja la escena en `aceptada_por_rendicion`, que **no es el
         *     mismo hecho** que `aceptada`: su delta entra igual al canon y quien lea el
         *     manuscrito despues necesita saber cuales fueron.
         */
        post: operations["aceptar_escenas__id_escena__aceptar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/escenas/{id_escena}/generar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generar
         * @description `202` y un identificador. Nunca el texto, y nunca sincrono.
         */
        post: operations["generar_escenas__id_escena__generar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/escenas/{id_escena}/rechazar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rechazar */
        post: operations["rechazar_escenas__id_escena__rechazar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/obras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Alta De Obra */
        post: operations["alta_de_obra_obras_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/obras/{id_obra}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar Obra */
        get: operations["consultar_obra_obras__id_obra__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/obras/{id_obra}/cambios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cambios
         * @description `202` con el identificador de trabajo. `409` si no hay salida elegida -hoy,
         *     siempre: falta la medida-, si la lista no es la propuesta o si `C-4` no la admite.
         *     Con `409` **no se guarda ni se encola nada**.
         */
        post: operations["cambios_obras__id_obra__cambios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/obras/{id_obra}/cambios/propuesta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Propuesta
         * @description Los capitulos que se van a tocar, **antes** de tocarlos, con la promesa y su
         *     punto ciego (`RF-51`, `RF-55`). Sincrona y sin modelo. `409` si `C-4` no la admite.
         */
        post: operations["propuesta_obras__id_obra__cambios_propuesta_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/obras/{id_obra}/entregar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Entregar
         * @description `SPEC-25` `RF-21`: borra la entrevista y conserva la novela, sus vetadas y
         *     sus hechos. Devuelve cuantas filas se borraron, nunca que contenian.
         */
        post: operations["entregar_obras__id_obra__entregar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/obras/{id_obra}/fichas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fichas
         * @description Las fichas de personajes y lugares, cada una con los capitulos donde aparece.
         */
        get: operations["fichas_obras__id_obra__fichas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/obras/{id_obra}/indice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Indice
         * @description La portada y el indice: capitulos por su orden, escenas con estado y hallazgos.
         */
        get: operations["indice_obras__id_obra__indice_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/obras/{id_obra}/progreso": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Progreso
         * @description En que punto va la generacion, con los segundos desde la ultima actividad. `404` si
         *     la obra no se ha empezado a generar: no se inventa una fase.
         */
        get: operations["progreso_obras__id_obra__progreso_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/obras/{id_obra}/versiones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Versiones
         * @description Las versiones con su numero, su anterior, su commit, cuando se crearon y su
         *     peticion (`RF-53`).
         */
        get: operations["versiones_obras__id_obra__versiones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/obras/{id_obra}/versiones/{numero}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Version
         * @description Los capitulos en orden: si es compartido con la anterior, su estado, y por
         *     escena su `estado_de_escena` y su `estado_de_verificacion` (`RF-52`..`RF-54`).
         */
        get: operations["version_obras__id_obra__versiones__numero__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trabajos/{id_trabajo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar Trabajo
         * @description El estado de un trabajo encolado: su resultado, o el motivo si fallo.
         *
         *     Es la otra mitad de todos los `202`: sin esto el cliente sabe que se encolo
         *     algo y no tiene forma de saber que paso.
         */
        get: operations["consultar_trabajo_trabajos__id_trabajo__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BorradorElegido
         * @description El `Borrador` elegido de la escena: el aceptado o, si no consta, el ultimo.
         */
        BorradorElegido: {
            /**
             * Texto
             * @description Byte a byte el del borrador, sin tocar (VER-60)
             */
            texto: string;
            /**
             * Version
             * @description Borrador.version: el ancla de una seleccion (RF-47)
             */
            version: number;
        };
        /**
         * BriefEntrada
         * @description Lo que hace falta para dar de alta una `Obra`.
         *
         *     Solo `titulo` y `premisa` son obligatorios, que es lo que dice la ficha de
         *     `Obra`. `persona` y `tiempo_verbal` son de `GuiaDeEstilo` y entran aqui
         *     porque sin ellos el Escaletador no puede empezar; el resto de la guia llega
         *     con su propia feature.
         */
        BriefEntrada: {
            /** Extension Objetivo */
            extension_objetivo?: number | null;
            /** Genero */
            genero?: string | null;
            persona?: components["schemas"]["PersonaNarrativa"] | null;
            /** Premisa */
            premisa: string;
            /** Subgenero */
            subgenero?: string | null;
            tiempo_verbal?: components["schemas"]["TiempoVerbal"] | null;
            /** Titulo */
            titulo: string;
        };
        /**
         * CambioEntrada
         * @description La misma peticion y la lista que el lector acepta, que tiene que ser la
         *     propuesta (`RF-48`, `RF-50`).
         */
        CambioEntrada: {
            /** Capitulos Propuestos */
            capitulos_propuestos: string[];
            clase: components["schemas"]["ClaseDePeticion"];
            /** Enunciado Nuevo */
            enunciado_nuevo?: string | null;
            /** Hecho */
            hecho?: string | null;
            /** Nombre Nuevo */
            nombre_nuevo?: string | null;
            /** Personaje */
            personaje?: string | null;
            /** Texto */
            texto: string;
            /** Version De Partida */
            version_de_partida?: number | null;
        };
        /** CapituloDeVersionSalida */
        CapituloDeVersionSalida: {
            /** Capitulo */
            capitulo: string;
            /** Compartido */
            compartido: boolean | null;
            /** Escenas */
            escenas: components["schemas"]["EscenaDeVersionSalida"][];
            estado: components["schemas"]["EstadoDeCapitulo"] | null;
            /** Orden */
            orden: number;
        };
        /** CapituloDelIndice */
        CapituloDelIndice: {
            /**
             * Escenas
             * @description En orden de lectura
             */
            escenas: components["schemas"]["EscenaDelIndice"][];
            estado: components["schemas"]["EstadoDeCapitulo"];
            /**
             * Id
             * @description El id del Capitulo; nunca el de la obra (RF-37)
             */
            id: string;
            /**
             * Orden
             * @description Orden de lectura; la lista ya viene en este orden
             */
            orden: number;
        };
        /**
         * CapituloEnlazado
         * @description Una referencia a un `Capitulo`: su id y su orden, para enlazarlo y nombrarlo.
         */
        CapituloEnlazado: {
            /**
             * Id
             * @description El id del Capitulo; nunca el de la obra (RF-37)
             */
            id: string;
            /** Orden */
            orden: number;
        };
        /**
         * CapituloLeido
         * @description Un capitulo de corrido: sus escenas en orden, **una por bloque** (`RF-41`).
         *
         *     Lo ensambla el backend -que escenas entran y en que orden-, pero no junta los
         *     textos: cada escena lleva el suyo con su estado y sus hallazgos (`RF-39`).
         */
        CapituloLeido: {
            /**
             * Escenas
             * @description En orden de lectura
             */
            escenas: components["schemas"]["EscenaLeida"][];
            estado: components["schemas"]["EstadoDeCapitulo"];
            /**
             * Id
             * @description El id del Capitulo; nunca el de la obra (RF-37)
             */
            id: string;
            /** Orden */
            orden: number;
        };
        /** CapitulosPorSalida */
        CapitulosPorSalida: {
            /** Cascada */
            cascada: string[];
            /** Selectiva */
            selectiva: string[];
        };
        /**
         * ClaseDePeticion
         * @description `C-4`: lo que el lector puede pedir. Un hecho o un nombre.
         * @enum {string}
         */
        ClaseDePeticion: "hecho" | "nombre";
        /** ContradiccionSalida */
        ContradiccionSalida: {
            /** Descripcion */
            descripcion: string;
            /** Tipo */
            tipo: string;
        };
        /** EscenaDeVersionSalida */
        EscenaDeVersionSalida: {
            estado: components["schemas"]["EstadoDeEscena"];
            estado_de_verificacion: components["schemas"]["EstadoDeVerificacion"];
            /** Id */
            id: string;
        };
        /**
         * EscenaDelIndice
         * @description Una escena en el indice: su estado y sus hallazgos, **nunca** sin ellos (`RF-39`).
         */
        EscenaDelIndice: {
            /**
             * Capitulo
             * @description El id del Capitulo que la contiene; nunca el de la obra. Nulo solo en escaletas anteriores a SPEC-21, que no lo guardaban
             */
            capitulo: string | null;
            estado: components["schemas"]["EstadoDeEscena"];
            /** Hallazgos Abiertos */
            hallazgos_abiertos: components["schemas"]["HallazgoAbierto"][];
            /** Id */
            id: string;
            /**
             * Se Acepto Rindiendose
             * @description Resuelto en el backend: estado == aceptada_por_rendicion (RF-40)
             */
            se_acepto_rindiendose: boolean;
        };
        /**
         * EscenaLeida
         * @description Una escena para leer: la del indice mas su texto. **Nunca** el texto sin estado.
         */
        EscenaLeida: {
            /** @description Nulo si la escena no tiene ningun borrador (p. ej. planificada) */
            borrador: components["schemas"]["BorradorElegido"] | null;
            /**
             * Capitulo
             * @description El id del Capitulo que la contiene; nunca el de la obra. Nulo solo en escaletas anteriores a SPEC-21, que no lo guardaban
             */
            capitulo: string | null;
            estado: components["schemas"]["EstadoDeEscena"];
            /** Hallazgos Abiertos */
            hallazgos_abiertos: components["schemas"]["HallazgoAbierto"][];
            /** Id */
            id: string;
            /**
             * Se Acepto Rindiendose
             * @description Resuelto en el backend: estado == aceptada_por_rendicion (RF-40)
             */
            se_acepto_rindiendose: boolean;
        };
        /**
         * EstadoDeCapitulo
         * @enum {string}
         */
        EstadoDeCapitulo: "abierto" | "cerrado";
        /**
         * EstadoDeEscena
         * @enum {string}
         */
        EstadoDeEscena: "planificada" | "generada" | "en_verificacion" | "rechazada" | "en_revision" | "aceptada" | "aceptada_por_rendicion" | "consolidada";
        /**
         * EstadoDeHallazgo
         * @enum {string}
         */
        EstadoDeHallazgo: "abierto" | "resuelto" | "descartado" | "sin_veredicto";
        /**
         * EstadoDeVerificacion
         * @description El estado de una escena **en una version**, que no es `estado_de_escena`.
         *
         *     `sin_reverificar` es el verde heredado de otra version: **no cuenta como verde**
         *     (`D-1`). No añade ninguna transicion a la maquina de `estado_de_escena`.
         * @enum {string}
         */
        EstadoDeVerificacion: "verificada" | "sin_reverificar" | "fallida";
        /**
         * EstadoVital
         * @enum {string}
         */
        EstadoVital: "vivo" | "muerto" | "desaparecido";
        /**
         * FaseDeGeneracion
         * @description En que punto va una generacion. `parada` lleva su motivo; `esperando_revision` es
         *     que el pipeline termino sin publicar y ahora le toca a una persona.
         * @enum {string}
         */
        FaseDeGeneracion: "planificando" | "revisando_plan" | "escribiendo" | "editando" | "resumiendo" | "en_la_puerta" | "publicada" | "parada" | "esperando_revision";
        /**
         * FichaDeLugar
         * @description `Lugar` (`RF-43`).
         */
        FichaDeLugar: {
            /**
             * Atmosfera
             * @description Nula: la base no la guarda
             */
            atmosfera: string | null;
            /**
             * Capitulos Donde Aparece
             * @description Por ocurre_en y Capitulo.orden (RF-44)
             */
            capitulos_donde_aparece: components["schemas"]["CapituloEnlazado"][];
            /** Id */
            id: string;
            /**
             * Nombre
             * @description Nulo si la base no lo guarda (PLAN-27 E2)
             */
            nombre: string | null;
        };
        /**
         * FichaDePersonaje
         * @description `Personaje` (`RF-43`). Lo que la base no guarda viaja nulo: «sin dato», no «ninguno».
         */
        FichaDePersonaje: {
            /**
             * Alias
             * @description Nulo: la base no guarda alias
             */
            alias: string[] | null;
            /**
             * Capitulos Donde Aparece
             * @description Por participa_en y Capitulo.orden. Nulo si la obra no declara sus personajes_presentes: no declarado, que no es nadie (RF-44)
             */
            capitulos_donde_aparece: components["schemas"]["CapituloEnlazado"][] | null;
            estado_vital: components["schemas"]["EstadoVital"] | null;
            /** Id */
            id: string;
            /**
             * Nombre Canonico
             * @description Nulo si la base no lo guarda (PLAN-27 E2)
             */
            nombre_canonico: string | null;
            /** @description Nulo: la base no lo guarda */
            rol_dramatico: components["schemas"]["RolDramatico"] | null;
        };
        /** Fichas */
        Fichas: {
            /** Lugares */
            lugares: components["schemas"]["FichaDeLugar"][];
            /** Personajes */
            personajes: components["schemas"]["FichaDePersonaje"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HallazgoAbierto
         * @description Un `Hallazgo` con estado `abierto` o `sin_veredicto`, con **su** estado.
         */
        HallazgoAbierto: {
            /** Descripcion */
            descripcion: string;
            /** @description sin_veredicto es que falto el juicio, no que se violara */
            estado: components["schemas"]["EstadoDeHallazgo"];
            /**
             * Invariante
             * @description La INV-xx que se violo o no se pudo comprobar
             */
            invariante: string;
            severidad: components["schemas"]["Severidad"];
            /**
             * Verificador
             * @description Quien lo detecto
             */
            verificador: string;
        };
        /** HistorialSalida */
        HistorialSalida: {
            /** Primera Pregunta */
            primera_pregunta: string;
            /** Turnos */
            turnos: components["schemas"]["TurnoDeEntrevistaSalida"][];
        };
        /**
         * Indice
         * @description La portada y el indice de una obra, resueltos (`RF-38`, `RF-46`).
         *
         *     No lleva partes: la base no tiene tabla `parte` y el plan de la novela regalo no las
         *     declara (`PLAN-22` cuestion 3). No se pinta lo que no hay.
         */
        Indice: {
            /**
             * Capitulos
             * @description Por Capitulo.orden
             */
            capitulos: components["schemas"]["CapituloDelIndice"][];
            /**
             * Dedicatoria
             * @description Nula si la obra no tiene; nunca un relleno
             */
            dedicatoria: string | null;
            /**
             * Id
             * @description El id de la Obra
             */
            id: string;
            /** Titulo */
            titulo: string;
        };
        /**
         * ObraSalida
         * @description Una obra nunca se devuelve sin su estructura.
         *
         *     `RF-23` lo dice para la escena -texto, estado y hallazgos abiertos, nunca el
         *     texto solo- y el motivo vale igual aqui: un dato suelto induce a darlo por
         *     bueno. Una obra recien creada devuelve `capitulos: []`, que es informacion,
         *     no un hueco.
         */
        ObraSalida: {
            /** Capitulos */
            capitulos?: string[];
            /** Genero */
            genero?: string | null;
            /** Id */
            id: string;
            /** Premisa */
            premisa: string;
            /** Titulo */
            titulo: string;
        };
        /**
         * PersonaNarrativa
         * @enum {string}
         */
        PersonaNarrativa: "primera" | "segunda" | "tercera_limitada" | "tercera_omnisciente";
        /**
         * PeticionEntrada
         * @description Los campos de `PeticionDeCambio` que da el lector. Con `hecho`, `hecho` y
         *     `enunciado_nuevo`; con `nombre`, `personaje` y `nombre_nuevo`. La obra va en la ruta
         *     y la version de partida, si no se dice, es la vigente.
         */
        PeticionEntrada: {
            clase: components["schemas"]["ClaseDePeticion"];
            /** Enunciado Nuevo */
            enunciado_nuevo?: string | null;
            /** Hecho */
            hecho?: string | null;
            /** Nombre Nuevo */
            nombre_nuevo?: string | null;
            /** Personaje */
            personaje?: string | null;
            /** Texto */
            texto: string;
            /** Version De Partida */
            version_de_partida?: number | null;
        };
        /**
         * ProgresoDeGeneracion
         * @description En que punto va la generacion de una obra (`SPEC-22` `RF-60`). Lo resuelve el
         *     servidor: la interfaz lo pinta y no resta fechas.
         */
        ProgresoDeGeneracion: {
            /**
             * Capitulo
             * @description Numero de capitulo (1-based), nulo fuera de uno
             */
            capitulo: number | null;
            /**
             * Desde
             * @description Cuando entro en la fase (UTC, AAAA-MM-DD HH:MM:SS)
             */
            desde: string;
            fase: components["schemas"]["FaseDeGeneracion"];
            /**
             * Motivo
             * @description Solo en parada: por que
             */
            motivo: string | null;
            /**
             * Obra
             * @description El id de la Obra
             */
            obra: string;
            /**
             * Segundos Desde La Ultima Actividad
             * @description Calculados por el servidor al responder, con su reloj
             */
            segundos_desde_la_ultima_actividad: number;
            /** Total De Capitulos */
            total_de_capitulos: number | null;
            /**
             * Ultima Actividad
             * @description Lo mas reciente entre la fase, las trazas y las llamadas a tool de la obra (UTC)
             */
            ultima_actividad: string;
        };
        /** PropuestaSalida */
        PropuestaSalida: {
            capitulos: components["schemas"]["CapitulosPorSalida"];
            /** Capitulos Propuestos */
            capitulos_propuestos: string[] | null;
            clase: components["schemas"]["ClaseDePeticion"];
            /** Motivo */
            motivo: string | null;
            /** Obra */
            obra: string;
            /** Promesa */
            promesa: string;
            /** Punto Ciego */
            punto_ciego: string;
            salida: components["schemas"]["SalidaDeRegeneracion"] | null;
            /** Version De Partida */
            version_de_partida: number;
        };
        /** RespuestaEntrada */
        RespuestaEntrada: {
            /** Respuesta */
            respuesta: string;
        };
        /**
         * RolDramatico
         * @enum {string}
         */
        RolDramatico: "protagonista" | "antagonista" | "aliado" | "guardian_del_umbral" | "victima" | "testigo";
        /**
         * SalidaDeRegeneracion
         * @description `S-1` y `S-2`. La elige la medida del arrastre (`SPEC-23` v2), no una opinion.
         * @enum {string}
         */
        SalidaDeRegeneracion: "cascada" | "selectiva";
        /**
         * Severidad
         * @enum {string}
         */
        Severidad: "bloqueante" | "mayor" | "menor";
        /**
         * TextoLibreEntrada
         * @description Sin `max_length`: el limite de `RF-11` lo comprueba `texto_libre`, que
         *     devuelve el motivo con las dos cifras. Un 422 generico de Pydantic diria que
         *     esta mal pero no cuanto sobra.
         */
        TextoLibreEntrada: {
            /** Texto */
            texto: string;
        };
        /**
         * TiempoVerbal
         * @enum {string}
         */
        TiempoVerbal: "presente" | "pasado";
        /**
         * TurnoDeEntrevistaSalida
         * @description `TurnoDeEntrevista` (`SPEC-33` `RF-10`). `pregunta` es la que el Entrevistador
         *     hizo **despues** de esta respuesta. `falta`, `avisos` y `contradicciones_abiertas` son lo
         *     que el codigo dijo en este turno; `None` si la fila es anterior a guardarlos.
         */
        TurnoDeEntrevistaSalida: {
            /** Avisos */
            avisos: string[] | null;
            /** Contradicciones Abiertas */
            contradicciones_abiertas: components["schemas"]["ContradiccionSalida"][] | null;
            /** Cuando */
            cuando: string | null;
            /** Falta */
            falta: string[] | null;
            /** Orden */
            orden: number;
            /** Pregunta */
            pregunta: string;
            /** Respuesta */
            respuesta: string;
            /** Tema */
            tema: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VersionDetalleSalida */
        VersionDetalleSalida: {
            /** Anterior */
            anterior: number | null;
            /** Capitulos */
            capitulos: components["schemas"]["CapituloDeVersionSalida"][];
            /** Commit */
            commit: string;
            /** Creada En */
            creada_en: string;
            /** Numero */
            numero: number;
            /** Obra */
            obra: string;
            /** Peticion */
            peticion: number | null;
        };
        /** VersionSalida */
        VersionSalida: {
            /** Anterior */
            anterior: number | null;
            /** Commit */
            commit: string;
            /** Creada En */
            creada_en: string;
            /** Numero */
            numero: number;
            /** Peticion */
            peticion: number | null;
        };
        /** VersionesSalida */
        VersionesSalida: {
            /** Obra */
            obra: string;
            /** Versiones */
            versiones: components["schemas"]["VersionSalida"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    capitulo_capitulos__id_capitulo__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_capitulo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapituloLeido"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cerrar_capitulo_capitulos__id_capitulo__cerrar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_capitulo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_entrevistas_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    consultar_entrevistas__id_e__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_e: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cerrar_entrevistas__id_e__cerrar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_e: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirmar_entrevistas__id_e__hechos__id_h__confirmar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_e: string;
                id_h: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    descartar_entrevistas__id_e__hechos__id_h__descartar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_e: string;
                id_h: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    texto_libre_entrevistas__id_e__texto_libre_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_e: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextoLibreEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    historial_entrevistas__id_e__turnos_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_e: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistorialSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    turno_entrevistas__id_e__turnos_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_e: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RespuestaEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    escena_escenas__id_escena__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_escena: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscenaLeida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    aceptar_escenas__id_escena__aceptar_post: {
        parameters: {
            query: {
                version: number;
                rindiendose?: boolean;
            };
            header?: never;
            path: {
                id_escena: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generar_escenas__id_escena__generar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_escena: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rechazar_escenas__id_escena__rechazar_post: {
        parameters: {
            query: {
                motivo: string;
            };
            header?: never;
            path: {
                id_escena: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alta_de_obra_obras_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BriefEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObraSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    consultar_obra_obras__id_obra__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_obra: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObraSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cambios_obras__id_obra__cambios_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_obra: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CambioEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    propuesta_obras__id_obra__cambios_propuesta_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_obra: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeticionEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropuestaSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    entregar_obras__id_obra__entregar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_obra: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fichas_obras__id_obra__fichas_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_obra: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fichas"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    indice_obras__id_obra__indice_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_obra: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Indice"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    progreso_obras__id_obra__progreso_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_obra: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgresoDeGeneracion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    versiones_obras__id_obra__versiones_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_obra: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionesSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    version_obras__id_obra__versiones__numero__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_obra: string;
                numero: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionDetalleSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    consultar_trabajo_trabajos__id_trabajo__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_trabajo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
